{% set name = "metatensor-torch" %}
{% set version = "0.9.0.rc5" %}
{% set upstream_version = "0.9.0rc5" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_torch-{{ upstream_version }}.tar.gz
  sha256: ac3fd68939b59f5a432fa08d8fc5491cd239dab10a656bc3c263fcc9bdecf0e9
  patches:
    - metatensor-torch-rc-cmake-version.patch

build:
  # conda-forge's libtorch is not yet available on Windows
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  script_env:
    # Don't build metatensor-torch, but use the already compiled `libmetatensor-torch`
    # package
    - METATENSOR_TORCH_PYTHON_USE_EXTERNAL_LIB="ON"

requirements:
  build:
    # Nothing will be built but we need a correct env to make pip happy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - setuptools >=77
    - packaging >=23
    # We build against the CPU version of torch to not have to deal with CUDA compilers
    # (torch's CMake targets tries to find CUDA compilers even when there is no CUDA
    # code to build). This does not impact the `run` dependency, since torch's
    # `run_exports` are variant agnostic
    - pytorch =2.10.*=cpu*
    - pip
    - libmetatensor-torch {{ version }}
    - python-metatensor-core >=0.2.0.rc3,<0.3.0
  run:
    - python
    - pytorch =2.10.*=cpu*
    - libmetatensor-torch {{ version }}
    - python-metatensor-core >=0.2.0.rc3,<0.3.0
    - python-vesin

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: Python bindings for metatensor-torch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: docs.metatensor.org

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
